### ISSUE TITLE
Unable to do aio app deploy due to SocketException

### ISSUE THREAD

**Issue by shelly-goel** [adobe/aio-cli-plugin-app#433] opened 2021-07-22 14:04 UTC
**Describe the bug**
While doing aio app deploy, certain machines are throwing SocketException. Verbose logs shared below:
It's happening always, used to work earlier. But now getting this error despite system restarts while it works fine on some machines for same codebase.

**Verbose Logs for aio app deploy**
$ aio app deploy --verbose
- Building actions
√ Building actions
- Building web assets
i bundling C:\Symphony\Code\adobe-content-symphony\web-src/index.html
- Building web assets
√ Building web assets
Build success, your app is ready to be deployed 👌
- Deploying actions
i Info: Deploying package [ContentAtScale-0.0.1]...
- Deploying actions
i Info: package [ContentAtScale-0.0.1] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/aio-lib-state-read]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/aio-lib-state-read] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/workfront-action]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/workfront-action] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/workfront-project-upload-handle]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/workfront-project-upload-handle] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/adobe-stock-search-action]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/adobe-stock-search-action] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/creative-cloud-search]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/creative-cloud-search] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/bookmark-action]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/bookmark-action] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/__secured_aio-lib-state-write]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/__secured_aio-lib-state-write] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/__secured_aem-assets-search]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/__secured_aem-assets-search] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/__secured_aem-projects-action]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/__secured_aem-projects-action] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/__secured_aem-assets-api]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/__secured_aem-assets-api] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/aio-lib-state-write]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/aio-lib-state-write] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/aem-assets-search]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/aem-assets-search] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/aem-projects-action]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/aem-projects-action] has been successfully deployed.
- Deploying actions
i Info: Deploying action [ContentAtScale-0.0.1/aem-assets-api]...
- Deploying actions
i Info: action [ContentAtScale-0.0.1/aem-assets-api] has been successfully deployed.
- Deploying actions
i Success: Deployment completed successfully.
- Deploying actions
√ Deploying actions
- Deploying web assets
i warning: an existing deployment will be overwritten
- Deploying web assets
i deploying index.html
- Deploying web assets
i deploying index.2a507c18.css
- Deploying web assets
i deploying index.fd6ebe80.css
- Deploying web assets
i deploying index.fd6ebe80.css.map
- Deploying web assets
i deploying index.2a507c18.css.map
- Deploying web assets
i deploying index.8c624348.css
- Deploying web assets
i deploying index.8c624348.css.map
- Deploying web assets
× Deploying web assets
    RequestTimeout: Your socket connection to the server was not read from or
    written to within the timeout period. Idle connections will be closed.
    Code: RequestTimeout

**Comment by meryllblanchet** [comment] 2021-07-22 14:52
Hi @shellygoelisobar , thanks for opening the issue.
We'll have a look and come back to you. Expect some delay as we are focusing on the last steps of an important release.

**Comment by meryllblanchet** [comment] 2021-08-05 08:42
Hi @shelly-goel , we cannot reproduce the issue on our side. Is it still happening for you?

**Comment by shelly-goel** [comment] 2021-08-06 06:39
@meryllblanchet  Yes it was consistently happening on one of the dev machine. Now the dev is not there on the team anymore. I would reach out in case we face the same issue again.

**Comment by meryllblanchet** [comment] 2021-08-06 08:17
Thanks @shelly-goel - it looks like an unfortunate issue on the underlying cloud storage to which the SPA files get deployed from the CLI. I'll close the issue for now, please reopen it as you propose, in case you would face it again.

**Closed by meryllblanchet** 2021-08-06 08:17 UTC
Labels: question
