### ISSUE TITLE
run shows logs from the last time I ran it

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app#293] opened 2020-09-14 22:11 UTC
**Describe the bug**
Running the app should only display logs that occur after the`run` command was run

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Himavanth** [comment] 2020-09-15 06:24
Is this a duplicate of https://github.com/adobe/aio-cli-plugin-app/issues/277 ?

**Comment by meryllblanchet** [comment] 2020-09-15 09:33
It looks like. @purplecabbage can you confirm and close this issue if it is the case? Thanks!

**Comment by meryllblanchet** [comment] 2020-09-16 05:24
Closing as discussed with @purplecabbage . Duplicate of #277 .

**Closed by meryllblanchet** 2020-09-16 05:24 UTC
